load File.join(File.dirname(File.realpath(__FILE__)), '..', '.flutter-plugins-dependencies')
load File.join(File.dirname(File.realpath(__FILE__)), 'Generated.podspec')

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end